class DescriptionService {
  generateDescription(gender) {
    const descriptions = {
      male: [
        'Ambitious entrepreneur - Uyo Creator Club',
        'Visionary Leader & Innovative Thinker - Uyo Creator Club',
        'Fearless Male Disruptor & Trendsetter - Uyo Creator Club',
        'Passionate Entrepreneur & Success Story - Uyo Creator Club',
        'Male Change Maker & Community Builder - Uyo Creator Club',
        'Innovative Mind & Strategic Thinker - Uyo Creator Club',
        'Courageous Male Trailblazer & Game Changer - Uyo Creator Club',
        'Talented Digital Maverick & Creative Genius - Uyo Creator Club',
        'Unstoppable Male Force & Entrepreneurial Spirit - Uyo Creator Club',
        'Inspiring Leader & Creative Visionary - Uyo Creator Club',
        'Male Mastermind & Innovative Thinker - Uyo Creator Club',
        'Adventurous Entrepreneur & Risk Taker - Uyo Creator Club',
        'Brilliant Male Mind & Creative Problem Solver - Uyo Creator Club',
        'Male Success Story & Inspirational Figure - Uyo Creator Club',
        'Fearless Male Entrepreneur & Leader - Uyo Creator Club',
        'Creative Male Genius & Innovative Spirit - Uyo Creator Club',
        'Male Trendsetter & Forward Thinker - Uyo Creator Club',
        'Passionate Male Change Maker & Activist - Uyo Creator Club',
        'Male Visionary & Strategic Leader - Uyo Creator Club',
        'Innovative Male Entrepreneur & Disruptor - Uyo Creator Club',
        'Male Tech Innovator & Digital Expert - Uyo Creator Club',
        'Dynamic Male Leader & Community Builder - Uyo Creator Club',
        'Courageous Male Entrepreneur & Risk Taker - Uyo Creator Club',
        'Talented Male Creative & Design Thinker - Uyo Creator Club',
        'Male Game Changer & Industry Disruptor - Uyo Creator Club',
        'Inspiring Male Role Model & Mentor - Uyo Creator Club',
        'Male Thought Leader & Innovative Visionary - Uyo Creator Club',
        'Adventurous Male Explorer & Entrepreneur - Uyo Creator Club',
        'Brilliant Male Mind & Strategic Thinker - Uyo Creator Club',
        'Male Success Story & Entrepreneurial Spirit - Uyo Creator Club',
        'Fearless Male Innovator & Trendsetter - Uyo Creator Club',
        'Creative Male Genius & Digital Maverick - Uyo Creator Club',
        'Male Change Maker & Social Entrepreneur - Uyo Creator Club',
        'Male Visionary Leader & Innovative Thinker - Uyo Creator Club',
        'Innovative Male Entrepreneur & Leader - Uyo Creator Club',
        'Male Mastermind & Creative Problem Solver - Uyo Creator Club',
        'Adventurous Male Entrepreneur & Change Maker - Uyo Creator Club',
        'Talented Male Digital Expert & Innovator - Uyo Creator Club',
        'Male Trailblazer & Game Changer - Uyo Creator Club',
        'Inspiring Male Leader & Creative Visionary - Uyo Creator Club',
        'Male Trendsetter & Innovative Spirit - Uyo Creator Club',
        'Passionate Male Entrepreneur & Community Builder - Uyo Creator Club',
        'Male Success Story & Inspirational Figure - Uyo Creator Club',
        'Fearless Male Disruptor & Entrepreneur - Uyo Creator Club',
        'Creative Male Genius & Thought Leader - Uyo Creator Club',
        'Male Visionary & Strategic Thinker - Uyo Creator Club',
        'Innovative Male Entrepreneur & Change Maker - Uyo Creator Club',
        'Male Mastermind & Digital Expert - Uyo Creator Club',
        'Adventurous Male Entrepreneur & Risk Taker - Uyo Creator Club',
        'Brilliant Male Mind & Creative Genius - Uyo Creator Club',
        ],
        female: [
          
          'Fearless Female Entrepreneur & Change Maker - Uyo Creator Club',
          'Innovative Female Mind & Strategic Thinker - Uyo Creator Club',
          'Passionate Female Activist & Community Builder - Uyo Creator Club',
          'Female Game Changer & Trendsetter - Uyo Creator Club',
          'Talented Female Creative & Digital Maverick - Uyo Creator Club',
          'Courageous Female Trailblazer & Leader - Uyo Creator Club',
          'Unstoppable Female Force & Entrepreneurial Spirit - Uyo Creator Club',
          'Inspiring Female Role Model & Mentor - Uyo Creator Club',
          'Female Mastermind & Innovative Thinker - Uyo Creator Club',
          'Adventurous Female Entrepreneur & Risk Taker - Uyo Creator Club',
          'Brilliant Female Mind & Creative Problem Solver - Uyo Creator Club',
          'Female Success Story & Inspirational Figure - Uyo Creator Club',
          'Fearless Female Disruptor & Trendsetter - Uyo Creator Club',
          'Female Visionary & Strategic Leader - Uyo Creator Club',
          'Innovative Female Entrepreneur & Leader - Uyo Creator Club',
          'Female Mastermind & Creative Problem Solver - Uyo Creator Club',
          'Adventurous Female Entrepreneur & Change Maker - Uyo Creator Club',
          'Talented Female Digital Expert & Innovator - Uyo Creator Club',
          'Female Trailblazer & Game Changer - Uyo Creator Club',
          'Inspiring Female Leader & Creative Visionary - Uyo Creator Club',
          'Female Trendsetter & Innovative Spirit - Uyo Creator Club',
          'Passionate Female Entrepreneur & Community Builder - Uyo Creator Club',
          'Female Success Story & Inspirational Figure - Uyo Creator Club',
          'Fearless Female Innovator & Entrepreneur - Uyo Creator Club',
          'Creative Female Genius & Thought Leader - Uyo Creator Club',
          'Female Visionary & Strategic Thinker - Uyo Creator Club',
          'Innovative Female Entrepreneur & Change Maker - Uyo Creator Club',
          'Female Mastermind & Digital Expert - Uyo Creator Club',
          'Adventurous Female Entrepreneur & Risk Taker - Uyo Creator Club',
          'Brilliant Female Mind & Creative Genius - Uyo Creator Club',
          'Empowered Female Leader & Innovative Thinker - Uyo Creator Club',
          'Female Game Changer & Industry Disruptor - Uyo Creator Club',
          'Inspiring Female Role Model & Mentor - Uyo Creator Club',
          'Female Thought Leader & Innovative Visionary - Uyo Creator Club',
          'Adventurous Female Explorer & Entrepreneur - Uyo Creator Club',
          'Talented Female Creative & Design Thinker - Uyo Creator Club',
          'Female Change Maker & Social Entrepreneur - Uyo Creator Club',
          'Female Visionary Leader & Innovative Thinker - Uyo Creator Club',
          'Innovative Female Entrepreneur & Leader - Uyo Creator Club',
          'Female Mastermind & Creative Problem Solver - Uyo Creator Club',
          'Adventurous Female Entrepreneur & Change Maker - Uyo Creator Club',
          ],
    };

    return descriptions[gender][Math.floor(Math.random() * descriptions[gender].length)];
  }

  generateAvatar(gender) {
    return gender === 'male' ? 'https://res.cloudinary.com/dwbthqy0f/image/upload/v1728647979/female_ab2wvq.jpg' : 'https://res.cloudinary.com/dwbthqy0f/image/upload/v1728647979/male_jxqv1g.jpg';
  }
}

module.exports = DescriptionService;